apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: gcpcloudtest2-ddns-net
spec:
  secretName: gcpcloudtest2-ddns-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gcpcloudtest2.ddns.net
  dnsNames:
    - gcpcloudtest2.ddns.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - gcpcloudtest2.ddns.net