apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cloudtest-ddns-net
spec:
  secretName: cloudtest-ddns-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: cloudtest.ddns.net
  dnsNames:
    - cloudtest.ddns.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - cloudtest.ddns.net